### PR TITLE
fix(auth): avoid "Error: Option 'redirectBareDomain' doesn't exist" on new installations

### LINKED ISSUE #1667: Receiving "Error: Option 'redirectBareDomain' doesn't exist" on new installation
### Description

On a fresh bare metal server installation without an initialized DB, I can see the following error in the background:

Image

The setup page still loads fine and all, so it's not a breaking error.

→ culprit found and PR is incoming in a couple minutes

### TriliumNext Version

git

### What operating system are you using?

Other Linux

### What is your setup?

Server access only

### Operating System Version

linux

### Error logs

_No response_

### PR DESCRIPTION
**Pull request by pano9000**
fixes #1667

### CODE REVIEW

File: src/services/auth.ts [hunk 1]
```diff
@@ -39,7 +39,9 @@ function checkAuth(req: Request, res: Response, next: NextFunction) {
         res.redirect('login');
         return;
     } else if (!req.session.loggedIn && !noAuthentication) {
-        const redirectToShare = options.getOptionBool("redirectBareDomain");
+
+        const redirectToShare = hasRedirectBareDomain();
```
Comment (eliandoran) [inline src/services/auth.ts:43]: Try simply `getOptionOrNull("redirectBareDomain") === "true"`.
It's not perfect, but good enough.
We can implement a `getOptionBoolOrNull` at some point.

Comment (pano9000) [reply src/services/auth.ts]: done in 1979affa8a6232b704c3a967ed3e14ce1a172d63

**Review by eliandoran — APPROVED** [review]
